---
title: мюсли | mueslii.ru
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
tagline: мудрые, вкусные
description: мудрые, вкусные
url: https://mueslii.github.io
baseurl: ''
author:
  name: Andrew Fong
  url: https://twitter.com/fongandrewc
paginate: 5
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
