# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            '![](/assets/logo.jpg)'
tagline:          'хоп!'
description:      'мудрые, вкусные'
url:              https://mueslii.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    'blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  ''   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
